name: tesafari
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.5
  localstorage: ^4.0.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.4
  provider: ^6.0.1
  easy_localization: ^3.0.0
  flutter_tabler_icons: ^1.1.1
  http: ^0.13.3
  cryptography: ^2.0.2
  flutter_local_notifications: ^11.0.1
  introduction_screen: ^3.0.0
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  encrypt: ^5.0.1
  universal_io: ^2.0.4
  platform: ^3.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_dotenv: ^5.0.2
  dropdown_search: ^5.0.2
  clickable_list_wheel_view: ^0.2.0
  sliding_up_panel: ^2.0.0+1
  share: ^2.0.4
  morphable_shape: ^1.6.4
  flutter_osm_plugin: ^0.40.2
  flutter_rating_bar: ^4.0.1
  mutex: ^3.0.0
  geocoding: ^2.0.5
  flutter_typeahead: ^4.1.1
  package_info_plus: ^3.0.0
  url_launcher: ^6.1.7
  flutter_native_splash: ^2.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/launchericon.png"

flutter_native_splash:
  color: '#3D5AFB'
  image: "lib/images/launchericon.png"


# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/
    - lib/translations/
    - lib/generated/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/fonts/static/Montserrat-Regular.ttf
        - asset: lib/fonts/static/Montserrat-Italic.ttf
          style: italic
        - asset: lib/fonts/static/Montserrat-Bold.ttf
          weight: 700  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
